version: '2'

services:
    cyoa-backend:
        container_name: cyoa-backend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "4208:8080"
            - "4209:443"

networks:
    cyoa-network:
        driver: bridge
