version: '2'

services:
    cyoa-backend:
        container_name: cyoa-backend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "4208:8080"
        networks:
            - cyoa-network
    mongo-db:
        container_name: mongo-db
        image: mongo
        volumes:
          - ./database:/data/db
        ports:
            - "27017:27017"
        networks:
            - cyoa-network

networks:
    cyoa-network:
        driver: bridge