services:
    cyoa-backend-db:
        image: "mongo:4.2"
        restart: always
        container_name: cyoa-backend-db
        env_file: .env
        environment:
            - MONGO_INITDB_DATABASE=cyoa-prod
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        ports:
            - "27017:27017"
        volumes:
            - "./database:/data/db"
        networks:
            - cyoa-network
    cyoa-backend:
        container_name: cyoa-backend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "4208:8080"
            - "4209:443"
        volumes:
            - "./uploads:/src/uploads"
        networks:
            - cyoa-network

networks:
    cyoa-network:
        driver: bridge
